# Generated automatically from Makefile.in by configure.
#
# This is a Gromacs 3.0 template makefile for your own utility programs.
#
# Copy this file to whatever directory you are using for your own
# software and add more targets like the template one below.
#
# If you are using gmake it is relatively straightforward to add
# an include based on environment variables (like previous Gromacs versions)
# to select compiler flags and stuff automatically, but below it is static:
#

# Variables set by the configuration script:
LIBS         = -lm -lmd -lgmx -lnsl -lfftw3f   
LDFLAGS      = -L/project/pomes/cneale/GPC/exe/intel/gromacs-4.0.5/exec/lib -L/project/pomes/cneale/GPC/exe/intel/fftw-3.1.2/exec/lib  
CFLAGS	     = -O3 -w -funroll-all-loops -std=gnu99  -I/project/pomes/cneale/GPC/exe/intel/gromacs-4.0.5/exec/include -I/project/pomes/cneale/GPC/exe/intel/gromacs-4.0.5/exec/include/gromacs	
CC           = cc
LD           = $(CC)

# The real make targets - note that most make programs support
# the shortcut $^ instead of listing all object files a second
# time, but we cannot count on it...

g_mdmat_g:	g_mdmat_g.o
		$(LD) $(LDFLAGS) -o /home/grace/bin/$@ g_mdmat_g.o $(LIBS)
		rm *.o
