#!/bin/sh

# Variables set by the configuration script:
LIBS         = -lmd -lgmx -lxml2  -L/usr/lib64 -R/usr/lib64 -lnsl   -lSM -lICE -lX11   
LDFLAGS      = -L/home/grace/bin/gromacs/4.0.7/lib   
CFLAGS	     = -O3 -tpp7 -axW -ip -w -funroll-all-loops   -I/usr/include/libxml2 -I/home/grace/bin/gromacs/4.0.7/include -I/home/grace/bin/gromacs/4.0.7/include/gromacs	
CC           = c++
LD           = $(CC)

BIN 	     = g_pp_nonpolar g_inositol_residue_nonpolar_v2 g_eed g_mdmat_g 
HOME         = /home/grace
# The real make targets - note that most make programs support
# the shortcut $^ instead of listing all object files a second
# time, but we cannot count on it...

all: g_inositol_residue_nonpolar_v2

#g_pp_nonpolar:  g_pp_nonpolar.o
#	$(LD) $(LDFLAGS) -o $(HOME)/bin/$@ g_pp_nonpolar.o $(LIBS)

g_inositol_residue_nonpolar_v2: g_inositol_residue_nonpolar_v2.o
	$(LD) $(LDFLAGS) -o $(HOME)/bin/$@ g_inositol_residue_nonpolar_v2.o $(LIBS)

g_eed: g_eed.o
	$(LD) $(LDFLAGS) -o $(HOME)/bin/$@ g_eed.o $(LIBS)

g_mdmat_g: g_mdmat_g.o
	$(LD) $(LDFLAGS) -o $(HOME)/bin/$@ g_mdmat_g.o $(LIBS)

clean:
	rm *.o $(BIN)
