#!/bin/sh

# Variables set by the configuration script:
LIBS         = -lxml2 -lmd -lgmx -lnsl -lfftw3f
LDFLAGS      = -L /project/p/pomes/cneale/GPC/exe/intel/gromacs-4.0.5/exec/lib -L /project/p/pomes/cneale/GPC/exe/intel/fftw-3.1.2/exec/lib
CFLAGS       = -ggdb3 -O3 -w -funroll-all-loops -std=gnu99  -I/project/p/pomes/cneale/GPC/exe/intel/gromacs-4.0.5/exec/lib -I/project/p/pomes/cneale/GPC/exe/intel/gromacs-4.0.5/exec/include/gromacs
CC           = c++
LD           = $(CC)

BIN 	     = g_pp_nonpolar g_inositol_residue_nonpolar_v2 g_eed g_mdmat_g 
HOME         = /home/p/pomes/grace
# The real make targets - note that most make programs support
# the shortcut $^ instead of listing all object files a second
# time, but we cannot count on it...

all: g_pp_nonpolar g_inositol_residue_nonpolar_v2

g_pp_nonpolar:  g_pp_nonpolar.o
	$(LD) $(LDFLAGS) -o $(HOME)/bin/$@ g_pp_nonpolar.o $(LIBS)

g_inositol_residue_nonpolar_v2: g_inositol_residue_nonpolar_v2.o
	$(LD) $(LDFLAGS) -o $(HOME)/bin/$@ g_inositol_residue_nonpolar_v2.o $(LIBS)

stacking: g_phe_stacking.o
	$(LD) $(LDFLAGS) -o $(HOME)/bin/$@ g_phe_stacking.o $(LIBS)

g_eed: g_eed.o
	$(LD) $(LDFLAGS) -o $(HOME)/bin/$@ g_eed.o $(LIBS)

g_mdmat_g: g_mdmat_g.o
	$(LD) $(LDFLAGS) -o $(HOME)/bin/$@ g_mdmat_g.o $(LIBS)

clean:
	rm *.o $(BIN)
