# Generated automatically from Makefile.in by configure.
#
# This is a Gromacs 3.0 template makefile for your own utility programs.
#
# Copy this file to whatever directory you are using for your own
# software and add more targets like the template one below.
#
# If you are using gmake it is relatively straightforward to add
# an include based on environment variables (like previous Gromacs versions)
# to select compiler flags and stuff automatically, but below it is static:
#

# Variables set by the configuration script:
LIBS         = -lmd -lgmx  -L/usr/X11R6/lib64 -lnsl -lfftw3f -lm   -lSM -lICE -lX11   
LDFLAGS      = -L/work/cneale/exe/gromacs-3.3.1/exec/lib -L/work/cneale/exe/fftw-3.1.2/exec/lib  
CFLAGS	     = -g -fomit-frame-pointer -finline-functions -Wall -Wno-unused -funroll-all-loops   -I/usr/X11R6/include  -I/work/cneale/exe/gromacs-3.3.1/exec/include/gromacs	
INCLU        = -I/work/cneale/exe/gromacs-3.3.1/exec/include/gromacs
CC           = c++
LD           = $(CC)
OBJS         = g_parse_index.o HB.o peptide.o hbgroup.o AminoAcid.o

g_parse_index: $(OBJS)
	$(LD) $(LDFLAGS) -o /home/grace/bin/$@ $(OBJS) $(LIBS)

HB.o: HB.cpp HB.h
	$(CC) -c $(INCLU) HB.cpp

peptide.o: peptide.cpp peptide.h AminoAcid.h HB.h
	$(CC) -c $(INCLU) peptide.cpp

hbgroup.o: hbgroup.cpp hbgroup.h
	$(CC) -c $(INCLU) hbgroup.cpp

AminoAcid.o: AminoAcid.cpp AminoAcid.h
	$(CC) -c $(INCLU) AminoAcid.cpp

